# Add building a package and pushing to PyPI with poetry following Typer docs https://bit.ly/3MTsoB2
name: Ninja Password

on:
  push:

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install poetry
          run: pipx install poetry
      - uses: actions/setup-python@v4
          with:
                python-version: '3.10'
                      cache: 'poetry'
      - run: poetry install
      - run: poetry run pytest
